# Generated by Django 5.1.7 on 2025-03-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('question', models.TextField()),
                ('com1', models.TextField()),
                ('com2', models.TextField()),
                ('com3', models.TextField()),
                ('theme1', models.TextField()),
                ('theme2', models.TextField()),
                ('theme3', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
