# Generated by Django 5.1.7 on 2025-03-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_generatedtext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AlterField(
            model_name='generatedtext',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
