# Generated by Django 5.1.7 on 2025-03-22 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('generatedtext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='members.generatedtext')),
            ],
            bases=('members.generatedtext',),
        ),
    ]
