# Generated by Django 5.1.7 on 2025-03-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_history'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
