apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: my-app
data:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: secret
  DB_HOST: postgres-service
  DB_PORT: "5432"
  EMAIL_PORT: "1025"
  OLLAMA_API_URL: "http://ollama-service:11434"
  SECRET_KEY: "django-insecure-jm433wwp8))t%gzvz*=%dlr&_2y43z&)9f76qmazd2d9ueresm"
