apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailhog-deployment
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailhog
  template:
    metadata:
      labels:
        app: mailhog
    spec:
      containers:
        - name: mailhog
          image: mailhog/mailhog
          ports:
            - containerPort: 1025
            - containerPort: 8025
---
apiVersion: v1
kind: Service
metadata:
  name: mailhog-service
  namespace: my-app
spec:
  selector:
    app: mailhog
  ports:
    - protocol: TCP
      port: 1025  # Port SMTP utilisé pour l'envoi de mails
      targetPort: 1025
      nodePort: 30025  # Port accessible sur les nœuds du cluster
    - protocol: TCP
      port: 8025  # Port HTTP pour l'interface web de MailHog
      targetPort: 8025
      nodePort: 30085  # Port HTTP accessible sur les nœuds du cluster
  type: NodePort